### ISSUE TITLE
Use Case Question 

### ISSUE THREAD

**Issue by JeffCarpenter** [FlipperPA/django-s3-sqlite#13]
Hi there, I see this is exactly the package I want and it is maintained at Wharton!

But I also see that it's not recommended for serious use.  So my question is, what would be a real life use case you've seen or an abstract example. Thanks!

**Comment by FlipperPA** [comment]
Hi @JeffCarpenter - I use it to maintain my personal blog at www.PyPhilly.org, for example. Others have used it for numerous things where the risk of concurrent writes isn't a danger.

This was also written before [Amazon introduced EFS](https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/). Using EFS would likely be a better option these days!
