### ISSUE TITLE
Offer pysqlite3-binary as a solution instead of compiling your own

### ISSUE THREAD

**Issue by pmdevita** [FlipperPA/django-s3-sqlite#15]
The Readme points to some instructions for building pysqlite3, but that may not actually be necessary. The [pysqlite3](https://github.com/coleifer/pysqlite3) project offers precompiled binaries, I was able to get things working through just `pip install pysqlite3-binary`.

pysqlite3 does not replace sqlite3 though and by default, it seems Django will still attempt to import the normal package. I had to [add these lines to my settings.py](https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300) to get it to work.

```
# these three lines swap the stdlib sqlite3 lib with the pysqlite3 package
__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
```

**Comment by YusufBilgin** [comment]
this worked for me

**Comment by FlipperPA** [comment]
I've added this to the README. Thank you!
