### ISSUE TITLE
Multiple lambdas accessing same db

### ISSUE THREAD

**Issue by emrebayramc** [FlipperPA/django-s3-sqlite#18]
Hey,
first of all thanks for the package;
i am trying to use this library for e2e tests instead of using the actual db.
my problem is i have multiple lambdas accessing to the same db and it looks like one can not see the change done by the other lambda.
i think it is because the library copies the db file from s3 to local temporarily and uploads back if it has changed.
One lambda is triggering the other lambda and i think the db updated by the first lambda is not being uploaded back on time.

curious any idea how to address this issue. can we force upload somehow before triggering the other lambda?

**Comment by FlipperPA** [comment]
@kazanture Unfortunately, that isn't going to work for the reasons you suspect. We're using a hack to make this work, and it is designed to be accessed by one Lambda function acting as webserver at a time. 

Issue #8 has some ideas on what we might be able to do, but I haven't had the cycles or need to explore it further.
