### ISSUE TITLE
'django_s3_sqlite' isn't an available database backend

### ISSUE THREAD

**Issue by makeev** [FlipperPA/django-s3-sqlite#3]
```
  raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'django_s3_sqlite' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

have this error wirh django==2.2.10
any suggestions?

**Comment by FlipperPA** [comment]
Did you add `django_s3_sqlite` to your `INSTALLED_APPS` list? I've forgotten to do that several times. :)

If not, can you include your Django settings file with anything sensitive blocked out? I'll try to create a solid repro. Thanks!

**Comment by FlipperPA** [comment]
Howdy @makeev, I just wanted to check in and see if you'd had any luck. If you came up with a solution, let me know what the problem was and I'll add it to the README. Thanks!

**Comment by jalr** [comment]
Got the same problem. You can run `zappa invoke --raw dev "from importlib import import_module; import_module('django_s3_sqlite.base')"` and see if you get a more descriptive error. In my case, `_sqlite3.so` depended on a python lib with a different version.

**Comment by FlipperPA** [comment]
@jalr @makeev We got a PR yesterday which includes a `_sqlite.so` build for Python 3.8, so we now have builds for both 3.6 and 3.8. Can you give those a try? I'm going to close this out, since we haven't heard from @makeev.

**Comment by viktor-idenfy** [comment]
Same issue, @FlipperPA . Django 3.15.
The issue is caused because of:
ImportError: dlopen(/Users/viktor/ess_core/_sqlite3.so, 2): no suitable image found.  Did find:
	/Users/user/test/_sqlite3.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/user/test/_sqlite3.so: stat() failed with errno=13
	
However I add it. Why it keeps setting unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00?

 Can you help?
